#  ┬─┐┬─┐┐ ┬┬─┐┬  ┌─┐┬─┐┌┌┐┬─┐┌┐┐┌┐┐
#  │ │├─ │┌┘├─ │  │ ││─┘│││├─ │││ │ 
#  ┘─┘┴─┘└┘ ┴─┘┘─┘┘─┘┘  ┘ ┘┴─┘┘└┘ ┘ 

nameOverride: lemon-juice
fullnameOverride: lemon-juice

image:
  tag: 1.22.1

apiKey: "developmentQWERTY"
replicas: 3
pdb:
  enabled: true
  maxUnavailable: 1
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
